### ISSUE TITLE
"Force user return from bank" question / issue

### ISSUE THREAD

**Issue by VMR-Global-Solutions** [TrogloGeek/prestashop-tggatos-module#1]
Hi,

I can't say if it's an issue, it's just maybe an error in our configuration.
When the "Force user return from bank" checkbox is checked, and when I pay, I'm automatically redirected to the order-history page, and the order is not confirm (the cart is still full & no new order in the backoffice).
If the "Force user return from bank" checkbox is NOT checked, everything works like a charme (but I have to click on "return to the shop" button in the bank summary page to confirm the order).

So, am I missing something ?

I've activated the Debug and in the "Request sent to the Payment Server" section I've the following info :
RETURN_URL (http://www.mydomain.com/modules/tggatos/autodispatch/userreturn.pub.php)
CANCEL_URL (http://www.mydomain.com/modules/tggatos/autodispatch/userreturn.pub.php)
AUTO_RESPONSE_URL (http://www.mydomain.com/module/tggatos/silentresponse)

I also don't have any error in the apache logs.

Any idea ?

Thanks a lot !

**Comment by TrogloGeek** [comment]
That looks like a problem laying in your redirection policies, possibly a canonical domain rule that don't keep get parameters as this problem is usually related to lost of bank information on return.
Are the domain in debug information (`RETURN_URL`, `CANCEL_URL` and `AUTO_RESPONSE_URL`) and the domain of history page you land on _exactly the same_ ? (same subdomains, same TLD)
There are also great chances that you have an issue with `suhosin` PHP patch which by default truncates long query string. Check if `suhosin` is installed and if `suhosin.get.max_value_length` is set high enough to receive bank `DATA` parameter, it defaults to 512 which is way too low. If you don't know how to check length of the received parameter, you can set it to 2048 or 4096 as usually SIPS 600 response are around 900-1000 chars length (which can vary, please check with your bank technical service the maximum length of the parameter they can send you before entering production mode).
There is another thing that bugs me in your issue : it looks like the silent response does not work, are you in Prestashop maintenance mode ? Do you use a worldwide routable domain name or are you testing with a non-routable domain (for exemple a fake domain you set in `hosts` configuration file of your computer) ?

Please provide the following information :
- Which git commit are you using ?
- Does this happen in demonstration and/or (pre-)production mode ?
- Name of the bank
- Does the problem happen with other banks' servers ?
- Other information requested in README.md after `Production use feedbacks with:`
- Could you provide module's log files of working and non working scenarios (generated in demonstration mode to avoid the share of personal information) ?
- Could you provide as well an `HAR` archive of HTTP transactions starting from clicking to card logo to get to bank server (please do this in demonstration mode to use a fake card number avoiding the share of personal information) and finishing on the page you land on when returning to your shop. Easier way to make one is to use Network tab of Chrome development tools :
  - When the logo of payment cards are displayed on your shop, open Chrome's development tools (F12), go to Network tab, make sure `Preserve Log upon Navigation` is activated in bottom bar.
  - Proceed with demonstration payment, simulate a successful transaction, keeping Chrome development tools opened.
  - When on order history page, right click the table of development tools and select `Copy all as HAR`

**Comment by TrogloGeek** [comment]
More information about HAR archives :
[What is a HAR File and what do I use it for?](http://www.speedawarenessmonth.com/what-is-a-har-file-and-what-do-i-use-it-for/)
[HAR W3.org specifications](https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/HAR/Overview.html)

**Comment by TrogloGeek** [comment]
Probably related to bugfix a64a196873a10bde32065968f2d637fae03db9bc
