### ISSUE TITLE
 n_time_payment error 

### ISSUE THREAD

**Issue by Nikusfr** [TrogloGeek/prestashop-tggatos-module#21]
Hello Damien, 

I tryed paiment in 2 and 3 time with the version 3.1 but the bank return the following message:  error check n_time_payment data (NB_PAYMENT=3;PERIOD=30;INITIAL_AMOUNT=3229660) 
INITIAL_AMOUNT too big (3229660/94990)

In tggatos.php i commented   $initialAmount *= 100;   to solve the problem

BR
Nicolas

**Comment by TrogloGeek** [comment]
Bonjour,

merci beaucoup pour ce retour,
effectivement, il y a un soucis lors du calcul sur le premier versement mais il ne vient pas de cette ligne-ci : le pourcentage saisi en back-office est appliqué comme un facteur et non un pourcentage (il n'est pas divisé par 100 avant d'être utilisé en facteur sur le montant) d'où la correspondance exacte avec le facteur 100 pour la gestion ATOS/SIPS des décimales (vrai uniquement si vous ne saisissez pas de montant fixe supplémentaire au pourcentage).
Je corrige.

**Comment by Nikusfr** [comment]
Bonjour Damien,
Merci pour la correction.
Salutations
Slts
Nicolas

**Comment by TrogloGeek** [comment]
I just managed to see that I answered you in french, sorry about that (weird thing, most of time I do the opposite: answer a french question in english, just because reading code makes me think in english...), probably because ATOS/SIPS documentation is in french. If any english reader would like a translation of the answer just let me know.
