### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by globule** [TrogloGeek/prestashop-tggatos-module#32]
Hi,
I use a FR version of Presta but the module admin is in english !
Any idea ?
(the module folder is "tggatos")

Laurent

**Comment by TrogloGeek** [comment]
Yes, I do not take care of translations, they're community driven, but so far only one contribution by @redpik : https://github.com/TrogloGeek/prestashop-tggatos-module/pull/15

Why?
Because it took me far too much time while handling the 1.x and 2.x versions to make sure I translated every new strings and to clean no more needed translations.
So 3.x is provided without translations.
In exchange, I try to be very reactive when a serious bug or security hole has to be worked on.

**Comment by bpongy** [comment]
bon courage, et merci pour tout ce taf!
