### ISSUE TITLE
Order ID

### ISSUE THREAD

**Issue by agnesdennetiere** [TrogloGeek/prestashop-tggatos-module#36]
Hello,
I had a small problem with your module: in the transaction list on my bank page, the transaction id is good , but the "order number" is not and I saw in your code that you use the cart id for the "order_id" parameter. 
Would it be possible to use the order id ?
Thank you

**Comment by TrogloGeek** [comment]
Hello,

sorry for the high latency, I had a complicated week, it was my last week at PrestaShop and had many things to transmit.

It would not be simple to use a real order_id because at the said order is created only when you receive the bank response. It would require converting the cart to order as soon as the user displays the page containing the CB logo which redirects you to the bank page, forbidding the user to go back and select another payment method or change his cart. It is feasible but would not fit very well to PrestaShop logic.
