### ISSUE TITLE
"Erreur interne du serveur de paiement"

### ISSUE THREAD

**Issue by Symediane** [TrogloGeek/prestashop-tggatos-module#44]
Hello,

I just added the "multistore" functionality on my preprod environment and since then, when I go to the bank payment page, I have an error "Erreur interne du serveur de paiement". Do you know if this is linked to the multistore feature ? Do we need to modify something for it to work ?
Thank you

**Comment by TrogloGeek** [comment]
Hello, I'm sorry I did not respond, your issue seems to have had a trek in a parallel universe were I could not see it... (I don't have a lot of time to spend on this project since I joined LiveMon).

Did you resolve your issue?
What are your PrestaShop and module versions?
Are you using demonstration or production mode?
Are you using your payment certificate on another website?

Reusing the same transaction ID the same day on the same certificate triggers an error (but not with this specific message I think), it happens when reusing a certificate on two different websites without spliting the transaction ID space, and happens a lot with demonstration certificate because they are not client specific (it is shared among ALL SIPS users for a given bank, so chances are someone may have already used the same transaction ID the same day).

I believe such error can be triggered when you use a language or a currency not supported by your SIPS gateway.

Best thing to do is to ask your SIPS support, providing the certificate number and date time of the failed payment request, they can look at their logs and tell you what was the problem. When they'll point at the faulty parameter I'll be able to help you.
