### ISSUE TITLE
Problem with the module on Prestashop 1.6

### ISSUE THREAD

**Issue by pat122** [TrogloGeek/prestashop-tggatos-module#59]
I have a big problem with the module, since the 18 of august the paiement process seems to work fine but at the end I have this message:
![capture d ecran 2016-08-26 a 10 11 53](https://cloud.githubusercontent.com/assets/21234529/17998690/f559f29a-6b75-11e6-8636-e2d16d21f70b.jpg)

"Payement won't work untill tomorrow"`. Is there anything I can do?
I called my Bank and they say the module should be upgraded but I don't see any "upgrade version".

**Comment by TrogloGeek** [comment]
Hello, either use PrestaShop debug mode or go to this module configuration interface to have more meaningful messages...

**Comment by pat122** [comment]
Hi, 
Thanks for your answer.
There are no more messages in the module configuration interface do I Will try Prestashop debug mode.

**Comment by TrogloGeek** [comment]
Did you also checked PrestaShop and PHP logs?

**Comment by pat122** [comment]
Yes I dis already and there is nothing there, at least nothing about the module.

**Comment by TrogloGeek** [comment]
When no errors are detected from back office but front office is failing, it is more than often a problem with the transaction ID generator. tggatos_transaction_today MySQL table may not be installed. Please make sure your MySQL server allows creation of MyISAM tables as InnoDB tables cannot handle an autoincrement column on a secondary Primary Key column. MyISAM is needed to generate reliable and multithread safe sequence based on the current day.

**Comment by pat122** [comment]
Sorry there are messages in the Prestashops Logs:

"/homez.534/milleetuc/www/modules/tggatos/tggatos.php(644): Error when
calling request ATOS binary, exit code was: 126ndebug object: 1 0 0x 0
2013-09-13 16:03:50 2 -- 1
/homez.534/milleetuc/www/modules/tggatos/tggatos.php(644): Error when
calling request ATOS binary, exit code was: 11ndebug

> Yes I dis already and there is nothing there, at least nothing about the
> module.
>

**Comment by TrogloGeek** [comment]
You can easily and quickly check if the problem lays in the sequence generator by using the advanced option from the module to disable the internal sequence generator and let SIPS binary handle it (not a wise choice for production shop as SIPS generator is absolutely not threadsafe, it uses current time in HHMMSS format which lead to errors when multiple users validate their carts at the same second).

**Comment by TrogloGeek** [comment]
Your log is really old: 2013-09-13 16:03:50, so nothing interesting here.

**Comment by pat122** [comment]
Ok I'm going to try that, The log is old I know.

**Comment by pat122** [comment]
I tried to let SIPS binary handle the transaction, but the result is the
same. I also checked the SQL and didn't find anything significant.

2016-08-26 11:53 GMT+02:00 Damien VERON notifications@github.com:

**Comment by pat122** [comment]
Would it be any help to delate the module and do a new installation ?

**Comment by pat122** [comment]
Hi,

are you still there? Would it help to do a new installation of the module?

**Comment by TrogloGeek** [comment]
It would help if you broke anything in it. Did you at least check your version is not obsolete?
You did not say which version you are using. Also, when you respond via email please delete your signature which pollute this thread and make it difficult to read.
What did the module say in front office when using debug mode?

**Comment by pat122** [comment]
Prestashop system says the version is ok, but who know's? Version is 3.0.1.
Is that ok?

Signature is disabled, the module in front office give the same message in
debug mode: "Payement will not work untill tomorow "

2016-08-26 17:23 GMT+02:00 Damien VERON notifications@github.com:

**Comment by TrogloGeek** [comment]
Your version is about 3 years old!
As you can see on this repository history and default branch, current version is 4.1.1 (4.1.2 being staged on branch RC_4.1.2).
Please consider updating before opening an issue on a release that old, when you sign with your agency name, its reputation is at stake.
It probably won't fix your problem, unless you had corrupted some file recently, but at least we won't be discussing about a code that old, I'd like to avoid checking all 35 commits separating current version from the 3.0.1 to remember what changed since if I can avoid it.

Did you also enabled the module debug options?

![image](https://cloud.githubusercontent.com/assets/3205686/18015103/73ec7920-6bc6-11e6-99ba-f182fdf04527.png)

**Comment by pat122** [comment]
Thanks for puting that into the light. where  can I download a recent version?

**Comment by pat122** [comment]
By the way, sorry for your time, Prestashop didn't say anything about updating this module!

**Comment by TrogloGeek** [comment]
PrestaShop will only warn you about updates from the Addons store, not from 3rd party modules. Git will.

To download the recent version clone the repository and follow https://github.com/TrogloGeek/prestashop-tggatos-module#installation-differences-with-a-simple-prestashop-module

**Comment by pat122** [comment]
Ok Thanks, I'll do that in the morning ( it's 22h in the evening now here)

**Comment by pat122** [comment]
Bonjour,

Je n'avais pas réalisé que nous pouvions parler français :) Merci pour votre aide, j'explore le blog en long et en large mais ne trouve pas de lien pour télécharger la mise à jour ...

**Comment by TrogloGeek** [comment]
I prefer communications here to be in English so more people have access to the knowledge base as there is a notable amount of technicians working with this module who are not at ease with French (mostly from Eastern Europe, India and North Africa).

The blog is obsolete, I don't use it anymore to release the module as it is really time consuming and I already spend a lot of time on this project support, maintenance and enhancement.

As said before, to get the last version of the module, use GIT to clone it from this GitHub repository. There are many documentations for beginners lying around to learn how to use GIT. Anyway to maintain a PrestaShop you really should be at ease with GIT, being the VCS used by PrestaShop.

SIPS gateway requires advanced technical skills regarding hosting environment due to the use of binaries as encryption handler, and a payment gateway is really something to take great care about. A security hole could lead to payments being hijacked. When messing with monetic systems you have legal responsibilities, you should probably pass on this task to a more experienced co-worker.

**Comment by pat122** [comment]
So, in simple words there is No update available ...

**Comment by TrogloGeek** [comment]
For the 3rd time, YES there are updates 4.1.1 and 4.1.2 available here on this specific repository. Use GIT to update.
