### ISSUE TITLE
response binary exit code 8

### ISSUE THREAD

**Issue by tucoinfo** [TrogloGeek/prestashop-tggatos-module#85]
Hello, does anyone know what this exit code means? Never had it till 2 days ago and it only happens from time to time.
`Error when calling response ATOS binary, exit code was: 8`

**Comment by TrogloGeek** [comment]
Hi, this is not a standard linux shell exit code and in the range [3;127] so it should be an actual SIPS binary return code. Someone else did contact me by email about the same problem happening once 28th may and another time the next day. I wonder if this could be an overflow of internal date storage, as SIPS is a pre-Y2K system, but if so it should be systematic from now on, did you have also successful response decoding happening as well?

As I myself don't have any SIPS merchant contract and SIPS technical support not being keen about answering to anyone but the contract owner, I asked the other module user to ask his bank technical contact about this. I'd like if you also ask your technical contact as I know you have better technical skills than him and should provide more useful details about your technical environment.

Is your module updated enough to have the full error logging system which logs the full response binary call command? If so, could you run it by hand via SSH to see if a command that failed once will always fail? That would help us knowing if the cause is environmental (current datetime or system resources pool status for example) or coded message specific. I expect it to be message specific as I think there is some coded variable that has grown too big for response binary to be able to handle it.

**Comment by tucoinfo** [comment]
Hi Damien, yes I have a parallel request for the binary's exit codes with Webaffaires Support. Ofcourse they just asked me for the transaction ID but I don't see how I can find it given that it's a POST and the payload is encrypted. Anyway, we just want the exit codes :-)

Command line execution of the 4 events [EDIT: 5 just now] in the error.log spits this:
`Exception de calcul en virgule flottante(core dumped)`

I checked the same command on a message in the CSV success logs and it decodes just fine. So it seems you might be right.

**Comment by TrogloGeek** [comment]
Are you using a 32bit version of SIPS binary, if so it would be worth checking if a real 64bits version exists, il the eventual overflow is on the response decoding side it could help. If an overflow occurred on bank side we're screwed.

**Comment by tucoinfo** [comment]
Yes 32bit. I just tried 64bit:
```
# file response64
response64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, for GNU/Linux 2.6.9, not stripped
```
but same result:
`Exception de calcul en virgule flottante(core dumped)`

This is FreeBSD 11.1 with linux compat.

**Comment by tucoinfo** [comment]
Update time. So Webaffaires/ATOS has still not responded to the additional test data I sent them. Which is unusual even if they are generally quite slow. Since then a second site started showing the same errors - then they **all** stopped... Maybe they fixed something. Wait and see.

**Comment by tucoinfo** [comment]
Webaffaires finally came back today with no answer to the question. Just that there was an incident and it was fixed on June 6th.
